### PR TITLE
Enforce a rule about specifying a second member.

### PR DESCRIPTION
**Pull request by djpetti**
This is in place for events that last for 24 hours or longer.
Currently, it uses the signup app user API to check if the user
is actually a member.

@billsaysthis: Please review.

### CODE REVIEW

**Comment by billsaysthis** [comment]
Looks really good to me. Wondering if you could add a test or two, to get that part started too.

**Comment by djpetti** [comment]
@billsaysthis: Please review.

**Comment by billsaysthis** [comment]
Terrific, looks good to me.

This gave me the idea of another to do for you: when you finish the stuff we've already discussed, try to set up TravisCI to run the tests automatically. If you need more detail on this let me know.

**Comment by djpetti** [comment]
Okay, I put that on my todo list.

**Pull request merged**
