### PR TITLE
Bulk actions

### PR DESCRIPTION
**Pull request by djpetti**
@billsaysthis: Please review.

This adds a bar to the top of various event views if you are an admin, which allows you to perform actions upon events in bulk.

Here is a screenshot of what it looks like:
2015-06-28-163319_1366x768_scrot

### CODE REVIEW

**Comment by billsaysthis** [comment]
I can't run the app. Getting an error trying to load the items listed in externals.txt, though I did run fab init after pulling the repo locally and before trying to launch it.

**Comment by djpetti** [comment]
Did you use `./deploy.py dev-server` to run it? That will download all the externals automatically.

**Comment by djpetti** [comment]
Oh, I forgot, you have to have pip installed too, but it should tell you if it can't find that...

**Comment by billsaysthis** [comment]
I've always used GAE App Launcher to run the app locally. If this is
changed please add the details to README.


Regards,
Bill Lazar
Events@

Please reply all to Events@ email so all concerned get your responses.

**Comment by djpetti** [comment]
Yes, the error message that it gives you when you try to do that actually says "Did you run using deploy.py?" at the end. Even so, I will put this in the README.

**Comment by billsaysthis** [comment]
I only saw that message because I looked in the App Launcher log viewer.
But not being  Python dev I'm not clear on how to fix it.


Regards,
Bill Lazar
Events@

Please reply all to Events@ email so all concerned get your responses.

**Comment by billsaysthis** [comment]
I opened a terminal and ran ./deploy.py dev-server but after downloading some files it errored out (trace below), when I ran from App Launcher got the same (previous) error about running deploy.py.

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1294, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 525, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1639, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/util.py", line 294, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Storing complete log in /Users/bill/Library/Logs/pip.log
ERROR: Installation of 'webtest' failed.```

**Comment by billsaysthis** [comment]
Also, I tried to install pip with easy_install but got "Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-10835.pth'", so I used sudo to install but running deploy.py after just raised "ERROR: Could not find 'pip'."

**Comment by djpetti** [comment]
Hmm, apparently it doesn't work so well on the Mac. I will have to test it on my dad's. (I always use it on Linux, so I don't really find out about these things very quickly...) Sorry about that. I'll get back to you shortly.

**Comment by djpetti** [comment]
Okay, it pretty much worked fine for me on the first try. I'm not sure what's happening for you. Does `which pip` produce output? If it can't find pip that would really screw it up, although I'm kind of confused because it appears from the error installing webtest that it got beyond that stage? What version of pip are you using? I installed mine using the source package, maybe we ended up with different versions or they were configured by default differently or something. That's the only explanation I can see for why it tried to install webtest in the completely wrong location. Also, it might be getting confused by partially-installed dependencies, although it should clean those up as soon as the installation fails. Try going into the externals directory and deleting everything except the .gitignore file and externals.txt.

**Comment by billsaysthis** [comment]
1. After sudo easy_install pip, which pip couldn't find a pip.
2. After I deleted that pip I tried sudo su -, then easy_install pip, which seemed to work.
3. After exiting the su session I ran ./deploy.py dev-server again and the tests ran but failed
4. From App Launcher I started the app again and the following is the log from that session:

```
*** Running dev_appserver with the following flags:
    --skip_sdk_update_check=yes --port=8080 --admin_port=8000
Python command: /usr/bin/python2.7
INFO     2015-07-04 01:30:54,920 devappserver2.py:762] Skipping SDK update check.
INFO     2015-07-04 01:30:54,998 api_server.py:204] Starting API server at: http://localhost:63197
INFO     2015-07-04 01:30:55,004 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2015-07-04 01:30:55,007 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR    2015-07-04 01:31:18,327 wsgi.py:263] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 354, in __getattr__
    self._update_configs()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 290, in _update_configs
    self._registry.initialize()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 165, in initialize
    import_func(self._modname)
  File "/Users/bill/Sites/hd-events/appengine_config.py", line 28, in <module>
    " Did you run using deploy.py?" % (external))
RuntimeError: Could not find external 'webtest == 2.0.18'. Did you run using deploy.py?
INFO     2015-07-04 01:31:18,337 module.py:812] default: "GET / HTTP/1.1" 500 -
INFO     2015-07-04 01:31:35,016 shutdown.py:45] Shutting down.
INFO     2015-07-04 01:31:35,017 api_server.py:629] Applying all pending transactions and saving the datastore
INFO     2015-07-04 01:31:35,017 api_server.py:632] Saving search indexes

*** Running dev_appserver with the following flags:
    --skip_sdk_update_check=yes --port=8080 --admin_port=8000
Python command: /usr/bin/python2.7
INFO     2015-07-04 01:32:09,601 devappserver2.py:762] Skipping SDK update check.
INFO     2015-07-04 01:32:09,668 api_server.py:204] Starting API server at: http://localhost:63230
INFO     2015-07-04 01:32:09,676 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2015-07-04 01:32:09,679 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR    2015-07-04 01:32:39,611 wsgi.py:263] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 354, in __getattr__
    self._update_configs()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 290, in _update_configs
    self._registry.initialize()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 165, in initialize
    import_func(self._modname)
  File "/Users/bill/Sites/hd-events/appengine_config.py", line 28, in <module>
    " Did you run using deploy.py?" % (external))
RuntimeError: Could not find external 'webtest == 2.0.18'. Did you run using deploy.py?
INFO     2015-07-04 01:32:39,621 module.py:812] default: "GET / HTTP/1.1" 500 -
INFO     2015-07-04 01:32:50,392 shutdown.py:45] Shutting down.
INFO     2015-07-04 01:32:50,392 api_server.py:629] Applying all pending transactions and saving the datastore
INFO     2015-07-04 01:32:50,392 api_server.py:632] Saving search indexes

*** Running dev_appserver with the following flags:
    --skip_sdk_update_check=yes --port=8080 --admin_port=8000
Python command: /usr/bin/python2.7
INFO     2015-07-04 04:48:08,450 devappserver2.py:762] Skipping SDK update check.
INFO     2015-07-04 04:48:08,518 api_server.py:204] Starting API server at: http://localhost:63777
INFO     2015-07-04 04:48:08,526 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2015-07-04 04:48:08,530 admin_server.py:118] Starting admin server at: http://localhost:8000
ERROR    2015-07-04 04:48:28,883 wsgi.py:263] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/Users/bill/Sites/hd-events/main.py", line 13, in <module>
    from models import Event, Feedback, HDLog, ROOM_OPTIONS, PENDING_LIFETIME
  File "/Users/bill/Sites/hd-events/models.py", line 5, in <module>
    from utils import human_username, local_today, to_sentence_list
  File "/Users/bill/Sites/hd-events/utils.py", line 4, in <module>
    import pytz
ImportError: No module named pytz
INFO     2015-07-04 04:48:28,894 module.py:812] default: "GET / HTTP/1.1" 500 -
INFO     2015-07-04 04:48:29,679 module.py:445] [default] Detected file changes:
  /Users/bill/Sites/hd-events/icalendar
```
And yes, I'm running OSX.

**Comment by djpetti** [comment]
Yeah, that's what it does when the externals don't install correctly. Did you try deleting all the subdirectories in externals? If you do that, can I see what the output is when it tries to install stuff?

**Comment by billsaysthis** [comment]
```
Sites/hd-events/externals(bulk_actions)» l                                                                    [8:14:34]
total 16
drwxr-xr-x   7 bill  staff   238B Jul  5 08:13 .
drwxr-xr-x  37 bill  staff   1.2K Jul  3 21:48 ..
-rw-r--r--   1 bill  staff    30B Jul  3 08:48 .gitignore
-rw-r--r--@  1 bill  staff    50B Jul  3 08:48 externals.txt
drwx------   5 bill  staff   170B Jul  5 08:13 pyRSS2Gen_v1.1
drwx------   2 bill  staff    68B Jul  5 08:13 pytz_v2015.4
drwx------   2 bill  staff    68B Jul  3 21:44 webtest_v2.0.18
Sites/hd-events/externals(bulk_actions)» ..                                                                   [8:14:36]
~/Sites/hd-events(bulk_actions)» ./deploy.py dev-server                                                       [8:14:39]
Using gae installation directory: /usr/local/bin/
test_main (unittest.loader.ModuleImportFailure) ... ERROR
test_models (unittest.loader.ModuleImportFailure) ... ERROR
test_utils (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_main (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_main
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/bill/Sites/hd-events/tests/test_main.py", line 17, in <module>
    import webtest
ImportError: No module named webtest


======================================================================
ERROR: test_models (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_models
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/bill/Sites/hd-events/tests/test_models.py", line 9, in <module>
    import models
  File "/Users/bill/Sites/hd-events/models.py", line 5, in <module>
    from utils import human_username, local_today, to_sentence_list
  File "/Users/bill/Sites/hd-events/utils.py", line 4, in <module>
    import pytz
ImportError: No module named pytz


======================================================================
ERROR: test_utils (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/bill/Sites/hd-events/tests/test_utils.py", line 6, in <module>
    import unittest, utils
  File "/Users/bill/Sites/hd-events/utils.py", line 4, in <module>
    import pytz
ImportError: No module named pytz


----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (errors=3)
ERROR: Unit tests failed.
```

**Comment by djpetti** [comment]
And deleting those last 3 subdirectories in externals doesn't change anything?

**Comment by billsaysthis** [comment]
Nope.
>
>

-- 

Regards,
Bill Lazar
Events@

Please reply all to Events@ email so all concerned get your responses.

**Comment by djpetti** [comment]
Okay, well, if you use `./deploy.py -f dev-server` you can force it to run dev_appserver even if the unit tests fail. If the unit tests are failing, I doubt that would help, but you can try it. Also, does installing all the packages with Pip succeed? If it doesn't, then that's the real problem.

**Comment by billsaysthis** [comment]
I tried installing from scratch on my work machine just now. The unit tests still fail, errors look the same as previously reported, running with -f or through AppLauncher gives a different (I think) error:
```
ERROR    2015-07-06 20:11:21,512 wsgi.py:262] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 239, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 353, in __getattr__
    self._update_configs()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 289, in _update_configs
    self._registry.initialize()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/api/lib_config.py", line 164, in initialize
    import_func(self._modname)
  File "/Users/blazar/Sites/hd-events/appengine_config.py", line 10, in <module>
    from google.appengine.ext import vendor
ImportError: cannot import name vendor
```

**Comment by djpetti** [comment]
Not sure why it's doing that thing with vendor. What version of pip are you using? If it doesn't take the right flags, then that could explain the failing installs.

**Comment by djpetti** [comment]
Oh, actually, you do appear to be using pip 1.4.1, based on some of the previous output you copied and pasted. That version doesn't support the --target option, which is why it's having problems installing stuff. You're going to want to run `sudo pip install --upgrade pip`. Then delete all the subdirectories from externals and try again. That should fix the dependencies not installing correctly.

**Comment by billsaysthis** [comment]
```
~/Sites/hd-events(bulk_actions)» pip -V                                                                                 [14:33:29]
pip 7.1.0 from /Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg (python 2.7)
```

**Comment by djpetti** [comment]
Oh, that's on your work machine though... So did it run all the pip stuff without failing on that one? It might just be easier to just delete all the subdirectories in externals, run deploy.py, and copy the entire output over here...

**Comment by billsaysthis** [comment]
```
~/Sites/hd-events(bulk_actions)» ./deploy.py dev-server                                                                 [14:39:05]
Using gae installation directory: /usr/local/bin/
Collecting webtest==2.0.18
/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached WebTest-2.0.18.zip
Collecting six (from webtest==2.0.18)
  Using cached six-1.9.0-py2.py3-none-any.whl
Collecting WebOb>=1.2 (from webtest==2.0.18)
  Using cached WebOb-1.4.1.tar.gz
Collecting waitress>=0.8.5 (from webtest==2.0.18)
  Using cached waitress-0.8.9.tar.gz
Collecting beautifulsoup4 (from webtest==2.0.18)
  Using cached beautifulsoup4-4.4.0-py2-none-any.whl
Collecting setuptools (from waitress>=0.8.5->webtest==2.0.18)
  Using cached setuptools-18.0.1-py2.py3-none-any.whl
Installing collected packages: six, WebOb, setuptools, waitress, beautifulsoup4, webtest
  Running setup.py install for WebOb
  Running setup.py install for waitress
  Running setup.py install for webtest
Successfully installed WebOb beautifulsoup4 setuptools-1.1.6 six-1.4.1 waitress webtest
Collecting pytz==2015.4
/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached pytz-2015.4-py2.py3-none-any.whl
Installing collected packages: pytz
Successfully installed pytz-2013.7
Collecting pyRSS2Gen==1.1
/Library/Python/2.7/site-packages/pip-7.1.0-py2.7.egg/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached PyRSS2Gen-1.1.tar.gz
Installing collected packages: pyRSS2Gen
  Running setup.py install for pyRSS2Gen
Successfully installed pyRSS2Gen
test_main (unittest.loader.ModuleImportFailure) ... ERROR
test_models (unittest.loader.ModuleImportFailure) ... ERROR
test_utils (unittest.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: test_main (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_main
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/blazar/Sites/hd-events/tests/test_main.py", line 6, in <module>
    import appengine_config
  File "/Users/blazar/Sites/hd-events/appengine_config.py", line 10, in <module>
    from google.appengine.ext import vendor
ImportError: cannot import name vendor


======================================================================
ERROR: test_models (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_models
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/blazar/Sites/hd-events/tests/test_models.py", line 9, in <module>
    import models
  File "/Users/blazar/Sites/hd-events/models.py", line 5, in <module>
    from utils import human_username, local_today, to_sentence_list
  File "/Users/blazar/Sites/hd-events/utils.py", line 6, in <module>
    from shared.api import domain
ImportError: No module named shared.api


======================================================================
ERROR: test_utils (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_utils
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/Users/blazar/Sites/hd-events/tests/test_utils.py", line 4, in <module>
    import appengine_config
  File "/Users/blazar/Sites/hd-events/appengine_config.py", line 10, in <module>
    from google.appengine.ext import vendor
ImportError: cannot import name vendor


----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=3)
ERROR: Unit tests failed.
```

**Comment by djpetti** [comment]
Okay, well, one problem is that you forgot to clone the shared library. (That really is kind of a pain.) I suppose running `fab init` should do that for you.

**Comment by djpetti** [comment]
Everything installed correctly though...

**Comment by billsaysthis** [comment]
```
~/Sites/hd-events(bulk_actions)» fab init                                                                               [14:42:41]
Traceback (most recent call last):
  File "/usr/local/bin/fab", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Fabric==1.8.0
```

**Comment by djpetti** [comment]
What a pain... Well, you can just do it manually:

`git submodule init`
`git submodule update`

**Comment by djpetti** [comment]
Also, what version of the appengine SDK are you using?

**Comment by djpetti** [comment]
Vendoring is a fairly new addition...

**Comment by billsaysthis** [comment]
- Running the submodule commands ran fine.
- 1.9.6
- ./deploy.py produced same errors (after running git commands), so did Launcher.

**Comment by djpetti** [comment]
Okay, I'm not sure if it will help, but will it break anything if you upgrade?

**Comment by djpetti** [comment]
Oh, the other trick you can use is running `deploy.py -t dev_server`. The -t option is actually intended to be used with Travis CI, so it downloads the SDK on-the-fly and uses that, then deletes it when it's done.

**Comment by billsaysthis** [comment]
Upgrade what, to what? (note: all this should go in the README, cannot assume new devs are set up more than what comes with Mac/Windows/Linux)

**Comment by djpetti** [comment]
Sorry, I meant `dev-server`, not `dev_server`...

**Comment by djpetti** [comment]
Upgrade the GAE SDK to the latest version. (I believe that's 1.9.23)

**Comment by billsaysthis** [comment]
ERROR: Could not find wget.

**Comment by djpetti** [comment]
Yeah, wget is not on Mac OSX by default. For that to work, you need to install it. It's probably just easier to upgrade the SDK.

**Comment by djpetti** [comment]
Before you go through that, though, let me just test to make sure that that is indeed your problem.

**Comment by billsaysthis** [comment]
Running the update function in the Launcher did the update, then I could launch the app. Yay!

**Comment by djpetti** [comment]
Oh, sweet!.

**Comment by djpetti** [comment]
I'm going to make deploy.py check that you have the correct version of the SDK installed, so nobody goes through this again.

**Comment by billsaysthis** [comment]
Cool.

So testing looks good, the visual is very nice considering I gave you no guidance. Even the UX designer sitting next to me really liked it.

Feedback:
- The toolbar (and checkboxes next to each item) should not appear on the default ('Approved') view,  only All Future and Pending. This is so moderating is only done in these two views.
- We seemed to have lost the 'by month' grouping of events this is not a good thing.

**Comment by djpetti** [comment]
Okay. Because of how the JavaScript handles updating the page when you take one of the actions, doing grouping is really annoying, which is why I initially took it out, but I can put it back in. Removing it from the approved view is simple enough.

**Comment by djpetti** [comment]
I've done a rebase so it should merge nicely. I also fixed a bug and disabled bulk actions in the "approved" view.

**Comment by djpetti** [comment]
So, date grouping is back in the approved view. Do we still need it in the pending, all, and not approved views?

**Comment by billsaysthis** [comment]
Would be great to have for All Future (i.e., if possible, please do this) and nice to have for Pending (i.e., if not too much additional work...).

**Comment by djpetti** [comment]
Okay, event grouping by date is back on all views.

**Comment by billsaysthis** [comment]
Looking nice but a couple of points to clean up:

- The checkbox is not properly positioned, should set vertical-align to baseline and padding-top to 6px
- Let's not repeat the date in the row for the event

**Comment by djpetti** [comment]
Okay. Please review.

**Comment by billsaysthis** [comment]
I'm not seeing any change for the checkbox positioning. I could be wrong but you may have put in CSS which isn't effective since the HTML for the TD has inline style="vertical-align: middle".

I'd change this so the style isn't inline; in general, I avoid them. Instead I conditionally add a class with the desired style.

Once you fix that please feel free to merge this. Yay!

**Pull request merged**
