### PR TITLE
Add support for recurring events.

### PR DESCRIPTION
**Pull request by djpetti**
It's pretty basic right now, but it seems to work okay. This is
made to the specifications that Bill outlined.

@billsaysthis: Please review.

### CODE REVIEW

**Comment by billsaysthis** [comment]
Trying to review this on my home machine but getting this error trying to start up the app:
```
~/Sites/hd-events(master)» ./deploy.py update
Using GAE installation directory: /usr/local/bin/
Traceback (most recent call last):
  File "./deploy.py", line 255, in <module>
    main()
  File "./deploy.py", line 225, in main
    version_info = file(os.path.join(gae_installation, "VERSION")).read()
IOError: [Errno 2] No such file or directory: u'/usr/local/bin/VERSION'
```

**Comment by djpetti** [comment]
Okay, try it again.

**Comment by billsaysthis** [comment]
Different error:

```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1294, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 525, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1639, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-1.4.1-py2.7.egg/pip/util.py", line 294, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

Storing complete log in /Users/bill/Library/Logs/pip.log
ERROR: Installation of 'webtest' failed.
```

**Comment by djpetti** [comment]
You need to upgrade your pip. Running `sudo pip install --upgrade pip` should do the trick...

**Comment by djpetti** [comment]
I think this was a problem before also, but we switched to your work computer, which had the proper version installed...

**Comment by billsaysthis** [comment]
Okay, worked, but you should note these required actions so I can review the PR without stumbling over them.

There are a couple of issues here:
- max value on number of occurences should be six.
- fields should be part of the existing form, just in a hidden div, otherwise changing them requires turning off the checkbox and turning back on so the member loses the previous settings.

**Comment by djpetti** [comment]
Okay, I don't quite understand your second comment. Note that you can change them without turning it off and on again, there is a little "edit" link next to it. Even if you do turn it off and on, you don't lose everything you entered, because everything IS stored in a hidden div, that div is just a bootstrap modal.

**Comment by billsaysthis** [comment]
Fair enough but my original spec said the fields should be inline.

**Comment by djpetti** [comment]
Right. I don't see why the separate modal causes problems, though. I think that long forms can overwhelm users, and it's nice to break things up a little. Plus, I was modeling my implementation off of Google Calendar, and this is how it's done there. It still has all the functionality you specified, just in a slightly different package.

**Comment by djpetti** [comment]
Oh, BTW, the max number of repetitions is fixed.

**Comment by billsaysthis** [comment]
a) fair enough for first pass
b) cool

**Comment by djpetti** [comment]
Okay, so are we good then? Does it do what you want?

**Comment by billsaysthis** [comment]
For a first pass, yes. We may want to refine after getting some people using it.

**Comment by djpetti** [comment]
Yeah, we'll see how it goes.

**Pull request merged**
